### ISSUE TITLE
Would you accept a complete implementation of the semver standard?

### ISSUE THREAD

**Issue by dmbaturin** [ashima/ocaml-semver#2]
I was looking for semver libraries, and found this one, but it can't compare versions like 1.0.0-beta.1 and 1.0.0-beta.2.3 as the semver standard requires.

Would you accept it if I implement it? The type in the module is not abstract so it would break backwards compatiblity, and the of_string function is going to be a lot more complex, so I'd rather ask first if this is consistent with your design goals.

**Comment by TikhonJelvis** [comment]
I haven't worked on this in a while. Rudi Grinberg has a fork that's up on Opam and presumably better-maintained: https://github.com/rgrinberg/ocaml-semver

I should probably link to his repo from the README or something.

**Comment by dmbaturin** [comment]
Yeah, that's another thing I wanted to ask about. The repository in the OPAM package metadata is that of @rgrinberg, but it's forked from yours, so it's not clear which one is really the mainline now.

**Comment by rgrinberg** [comment]
@dmbaturin I would accept a full semver implementation but I'd prefer if the old implementation is still kept for simpler use cases. Perhaps rename it `Semver_simple` or something.

I don't think break compatibility is a problem because we don't have downstream opam dependencies yet.

**Comment by rgrinberg** [comment]
Also, I've enabled the issue tracker in my fork.

**Comment by dmbaturin** [comment]
Ok, I'll re-create the issue in your fork then.
